paises_dictaduras = [
    "Afganistán",
    "Arabia Saudita",
    "Argelia",
    "Angola",
    "Azerbaiyán",
    "Baréin",
    "Bangladés",
    "Bielorrusia",
    "Brunéi",
    "Burundi",
    "Camboya",
    "Camerún",
    "República Centroafricana",
    "Chad",
    "China",
    "Cuba",
    "Yibuti",
    "República Democrática del Congo",
    "Egipto",
    "Guinea Ecuatorial",
    "Eritrea",
    "Esuatini (Suazilandia)",
    "Etiopía",
    "Gabón",
    "Irán",
    "Irak",
    "Jordania",
    "Kazajistán",
    "Kirguistán",
    "Laos",
    "Libia",
    "Birmania (Myanmar)",
    "Nicaragua",
    "Corea del Norte",
    "Omán",
    "Catar",
    "República del Congo",
    "Rusia",
    "Ruanda",
    "Arabia Saudita",
    "Somalia",
    "Sudán del Sur",
    "Sudán",
    "Siria",
    "Tayikistán",
    "Turquía",
    "Turkmenistán",
    "Uganda",
    "Emiratos Árabes Unidos",
    "Uzbekistán",
    "Venezuela",
    "Vietnam",
    "Sahara Occidental",
    "Yemen",
]


def generar_saludo(nombre: str, edad: int, pais: str = "España") -> str:
    if pais in paises_dictaduras:
        return f"Saludos {nombre}, te daremos asilo político."
    return f"Saludos {nombre}, tienes {edad} años y eres de {pais}."
